export default {
  /* test */
  FETCH_TEXT: "FETCH_TEXT",

  /* app global state */
  TOGGLE_SIDE_BAR: "TOGGLE_SIDE_BAR",
  SWITCH_SIDE_BAR_ITEM: "SWITCH_SIDE_BAR_ITEM",

  /* auth */
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  AUTO_LOGIN: "AUTO_LOGIN",

  /* mail */
  FETCH_MAIL_LIST: "FETCH_MAIL_LIST",
  MAIL_ERROR: "MAIL_ERROR",

  /* error */
  AUTH_ERROR: "AUTH_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR"
};
